spring:
  application:
    name: iris-tool-gateway


server:
  port: 9000


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.silas.iris.toolgateway

iris:
  bearer-token: ${IRIS.BEARER_TOKEN}
